spring.application.name=backend

# Thông tin kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/money_tracker
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (JPA)
# 'validate' giúp kiểm tra code Java có khớp với bảng SQL bạn vừa tạo không
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

